# Generated by Django 3.1.7 on 2021-04-06 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20210331_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='date_time',
        ),
        migrations.AddField(
            model_name='submissions',
            name='submit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
