# Generated by Django 3.1.7 on 2021-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_auto_20210406_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
